dataset: cifar10
architecture:
  name: ResNet
  depth: 20
device: cuda

# Minimisation
minima_count: 10
minimum:
  nsteps: 64000
  algorithm:
    name: SGD
    lr: 0.1
    momentum: 0.9
  scheduler:
    name: MultiStepLR
    milestones:
      - 32000
      - 48000
  eval:
    batch_size: 128

# Landscape exploration
exploration:
  value_key: train_loss
  weight_key: saddle_train_loss
  suggest:
    - unfinished
    - disconnected
    - mst
  autoneb:
    # The first cycle should contain all information, subsequent cycles only _differences_ from the previous
    # 3 times 2000 steps with lr=0.1
    - insert:
        name: equal
        count: 15
      subsample_pivot_count: 1
      spring_constant: inf
      weight_decay: 0.0001
      optim:
        nsteps: 2000
        algorithm:
          name: SGD
          lr: 0.1
          momentum: 0.9
        eval:
          batch_size: 512
    - insert:
        count: 0
    - {}
    # 2 times lr=0.01
    - optim:
        algorithm:
          lr: 0.01
      insert:
        name: highest
        key: dense_train_loss
        count: 2
    - insert:
        count: 0
    # 2 times lr=0.001
    - optim:
        algorithm:
          lr: 0.001
      insert:
        count: 2
    - insert:
        count: 0

