dataset: cifar10
architecture:
  name: CNN
  conv_depth: 1
  num_filters: 96
  filter_size: 5
  padding_size: 2
  pool_size: 2
  dense_depth: 1
  num_dense_units: 256
device: cuda

# Minimisation
minima_count: 10
minimum:
  nsteps: 64000
  algorithm:
    name: SGD
    lr: 0.1
    momentum: 0.9
  scheduler:
    name: MultiStepLR
    milestones:
      - 32000
      - 48000
  eval:
    batch_size: 128

# Landscape exploration
exploration:
  value_key: train_loss
  weight_key: saddle_train_loss
  suggest:
    - unfinished
    - disconnected
    - mst
  autoneb:
    # The first cycle should contain all information, subsequent cycles only _differences_ from the previous
    # 4 times 1000 steps with lr=0.1
    - insert:
        name: equal
        count: 3
      subsample_pivot_count: 9
      spring_constant: inf
      optim:
        nsteps: 1000
        algorithm:
          name: SGD
          lr: 0.1
          momentum: 0.9
        eval:
          batch_size: 512
    - insert:
        name: highest
        count: 2
        key: dense_train_loss
    - {} # same as previous
    - {}
    # 2 times 2000 steps with lr=0.1
    - optim:
        nsteps: 2000
    - {}
    # 4 times lr=0.01
    - optim:
        nsteps: 1000
        algorithm:
          lr: 0.01
    - {}
    - {}
    - {}
    # 4 times lr=0.001
    - optim:
        algorithm:
          lr: 0.001
    - {}
    - {}
    - {}

